name: deploy-heroku
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - numpy
  - pandas
  - scikit-learn
  - pytest
  - requests
  - fastapi==0.63.0
  - uvicorn
  - pip
  - pip:
    - gunicorn
